export const CATEGORIES = [
  "3D Modeling",
  "AI Agents",
  "AI Art",
  "AI Assistant",
  "AI Code",
  "AI Characters",
  "AI Image",
  "AI Music",
  "AI Research",
  "AI Search",
  "AI Tools",
  "AI Video",
  "AI Voice",
  "AI Writing",
  "Analytics",
  "Anime",
  "API",
  "Article",
  "Automation",
  "Biology",
  "Books",
  "Browser Extension",
  "Business",
  "Car Tools",
  "Cheatsheets",
  "Chemistry",
  "Chrome Extension",
  "Comparison",
  "Cooking",
  "Courses",
  "Database",
  "Data Sharing",
  "Design",
  "E-commerce",
  "Education",
  "Entertainment",
  "Fashion",
  "Finance",
  "Fitness",
  "Food",
  "Formula",
  "Free",
  "Freemium",
  "Fun",
  "Gaming",
  "Health",
  "History",
  "Hosting",
  "Icons",
  "Image",
  "Image Editing",
  "Image Tool",
  "Language Learning",
  "LLM",
  "Login Required",
  "Logo Creation",
  "Marketing",
  "Math",
  "Movie",
  "Music",
  "News",
  "No Code",
  "No Login Required",
  "Open Source",
  "PDF",
  "PDF Editing",
  "Photography",
  "Podcast",
  "Presentation",
  "Premium",
  "Privacy and Security",
  "Productivity",
  "Programming",
  "Programming Tricks",
  "Prank",
  "Radio",
  "Research",
  "Resume Builder",
  "Social Media",
  "Software Development",
  "Study",
  "Study Notes",
  "Summarizer",
  "Teaching",
  "Templates",
  "Tools",
  "Translation",
  "Travelling",
  "Typing",
  "UI",
  "Video Editing",
  "Video Tools",
  "Web Dev",
  "Wifi",
  "Writing Tool",
];

export const TESTIMONIALS = [
  {
    _id: "1",
    name: "Sarah Jenkins",
    role: "PRODUCT DESIGNER",
    content:
      "Web Hunter has completely changed how I source inspiration for my projects. No more generic search results.",
    avatarSeed: "sarah",
  },
  {
    _id: "2",
    name: "Marcus Thorne",
    role: "GROWTH LEAD",
    content:
      "The curation is top-tier. I found three incredible tools for my workflow within the first ten minutes of joining.",
    avatarSeed: "marcus",
  },
  {
    _id: "3",
    name: "Lila Chen",
    role: "CREATIVE DIRECTOR",
    content:
      "A breath of fresh air for the internet. It feels like the old days of stumbling upon gems, but professionally organized.",
    avatarSeed: "lila",
  },
];

export const TEMP = [
  {
    _id: "1",
    name: "ChatGPT",
    url: "https://chat.openai.com",
    description: "The most popular AI chatbot",
    tags: ["AI", "Chatbot"],
    isPremium: true,
    likesCount: 100,
    createdAt: "2022-01-01",
  },
  {
    _id: "2",
    name: "Gemini",
    url: "https://gemini.google.com",
    description: "Google's AI chatbot",
    tags: ["AI", "Chatbot"],
    isPremium: false,
    likesCount: 50,
    createdAt: "2022-01-01",
  },
  {
    _id: "3",
    name: "ChatGPT",
    url: "https://chat.openai.com",
    description: "The most popular AI chatbot",
    tags: ["AI", "Chatbot"],
    isPremium: true,
    likesCount: 100,
    createdAt: "2022-01-01",
  },
  {
    _id: "4",
    name: "Gemini",
    url: "https://gemini.google.com",
    description: "Google's AI chatbot",
    tags: ["AI", "Chatbot"],
    isPremium: false,
    likesCount: 50,
    createdAt: "2022-01-01",
  },
  {
    _id: "5",
    name: "ChatGPT",
    url: "https://chat.openai.com",
    description: "The most popular AI chatbot",
    tags: ["AI", "Chatbot"],
    isPremium: true,
    likesCount: 100,
    createdAt: "2022-01-01",
  },
  {
    _id: "6",
    name: "Gemini",
    url: "https://gemini.google.com",
    description: "Google's AI chatbot",
    tags: ["AI", "Chatbot"],
    isPremium: false,
    likesCount: 50,
    createdAt: "2022-01-01",
  },
];
